name: salva_GithubActions
on: 
  push:
   branches:
    - main
jobs:
  linter-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install -D
      - name: execute linter
        run: npm run lint

  Cypress_job:
    runs-on: ubuntu-latest
    needs: linter-job
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm run start
        id: res_cypress
        continue-on-error: true
      - run: echo ${{steps.res_cypress.outcome}} > result.txt