name: salva_GithubActions
on: 
  push:
   branches:
    - main
jobs:
  linter-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install -D
      - name: execute linter
        run: npm run lint

  Cypress_job:
    runs-on: ubuntu-latest
    needs: linter-job
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - uses: cypress-io/github-action@v5
        with:
          build: npm run build
          start: npm run start
        id: res_cypress
        continue-on-error: true
      - run: echo ${{steps.res_cypress.outcome}} > result.txt
      - uses: actions/upload-artifact@v3
        with:
          name: result.txt
          path: result.txt

  Add_badge_job:
    runs-on: ubuntu-latest
    needs: Cypress_job
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: result.txt
      - run: echo "::set-output name=cypress_outcome::$(cat result.txt)"
        id: cypress_result
      - uses: ./.github/actions/add_badge
        with:
          cypress_result: ${{steps.cypress_result.outputs.cypress_outcome}} 
      - uses: EndBug/add-and-commit@v9
        with:
          add: "."
          author_name: "Salva Muñoz Úbeda"
          message: "Cypress test result updated"
          push: true

  Deploy_job:
    runs-on: ubuntu-latest
    needs: Cypress_job
    steps:
      - uses: actions/checkout@v3
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          working-directory: ./

  Notification_job:
    runs-on: ubuntu-latest
    needs: [linter-job, Cypress_job, Add_badge_job, Deploy_job]
    if: always()
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/email
        with:
          linter_job: ${{ needs.linter-job.result }}
          cypress_job: ${{ needs.Cypress_job.result }}
          add_badge_job: ${{ needs.Add_badge_job.result }}
          deploy_job: ${{ needs.Deploy_job.result }}
          destinatario: "salmu1997@gmail.com"
          API_KEY: ${{ secrets.API_KEY_MAILGUN }}
          DOMAIN: ${{ secrets.DOMAIN_KEY_MAILGUN }}